### ISSUE TITLE
Handling parsed tap output

### ISSUE THREAD

**Issue by andrewdeandrade** [conradz/wd-tap-runner#1]
@conradz So I started using this module, but one thing I was hoping would be easy to deal with is the parsed tap output. Looking around the npm ecosystem, it looks like pretty much every module out there operates on raw tap output, using tap-parser internally as stream, converting the parsed output as it comes in. Now, having dug into `wd-tap-runner`, then `wd-tap`, then `tap-finished`, it looks like it's not even your call to produce parsed tap output since that is the only option offered by substack's `tap-finished`. 

With that in mind, do you know of any modules that operate directly on the completed parsed tap output? I looked around and couldn't find a single one. Even every module I found that uses tap-parser internally only operates on a streams and not the complete tap-parser results object. I would prefer not to have to write a stringifier for tap-parse, but that looks like the only option available to me right now. Since you wrote this module, I reckon you'd have a better idea of options available here.

**Comment by conradz** [comment]
Should this be closed now that conradz/wd-tap#3 is closed?

**Comment by andrewdeandrade** [comment]
This can be closed since `require('tap').Producer.encode(results)` solves the problem of re-encoding, but I did re-open conradz/wd-tap#3 since it is still useful since `tap-parser` is lossy with respect to user test comments.
